"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var carrinho_js_1 = require("../../classes/carrinho.js");
var item_js_1 = require("./../../classes/item.js");
var meuCarrinho = new carrinho_js_1.carrinho();
var item1 = new item_js_1.item("Mouse Gamer", "Periféricos", 150, 2);
var item2 = new item_js_1.item("Teclado Mecânico", "Periféricos", 350, 1);
var item3 = new item_js_1.item("Monitor", "Display", 1200, 1);
meuCarrinho.additem(item1);
meuCarrinho.additem(item2);
meuCarrinho.additem(item3);
console.log("Carrinho inicial:");
meuCarrinho.listar();
console.log("\nRemovendo 1 unidade do Mouse Gamer:");
meuCarrinho.remover("Mouse Gamer", 1);
meuCarrinho.listar();
console.log("\nRemovendo mais 1 unidade do Mouse Gamer:");
meuCarrinho.remover("Mouse Gamer", 1);
meuCarrinho.listar();
console.log("\nTentando remover um item inexistente:");
meuCarrinho.remover("Headset", 1);
console.log("\nRemovendo item do índice 0:");
meuCarrinho.delete(0);
meuCarrinho.listar();
